import type { Product, Review } from "./ecosphere-store";

export const SEED_PRODUCTS: Product[] = [
  {
    id: "p-bamboo-keyboard",
    title: "Bamboo Wireless Keyboard",
    shortDescription: "Handcrafted bamboo keys with ultra-quiet mechanical switches.",
    fullDescription:
      "A fully wireless keyboard built with sustainably harvested Moso bamboo. Each key is hand-finished and treated with plant-based oils. Silent tactile switches, 90-hour battery life on a single USB-C charge, and a replaceable battery cell to keep it in service for a decade.",
    price: 129,
    category: "Bamboo Tech",
    image: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=800&q=70",
    gallery: [
      "https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=1200&q=70",
      "https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?auto=format&fit=crop&w=1200&q=70",
      "https://images.unsplash.com/photo-1595225476474-87563907198a?auto=format&fit=crop&w=1200&q=70",
    ],
    ecoScore: 5,
    rating: 4.7,
    reviewsCount: 128,
    ownerId: "seed",
    specs: {
      Material: "FSC-certified Moso bamboo",
      Battery: "Replaceable Li-ion, 90h life",
      Connectivity: "Bluetooth 5.3 + USB-C",
      Weight: "820 g",
      Warranty: "10 years",
    },
  },
  {
    id: "p-solar-lantern",
    title: "Solar Camping Lantern",
    shortDescription: "Foldable solar-powered lantern with 40-hour runtime.",
    fullDescription:
      "A collapsible silicone lantern that charges from the sun in 6 hours and runs 40 hours on low. Waterproof to IP68, USB-C backup input, and doubles as a phone charger. Built from recycled ocean plastics.",
    price: 45,
    category: "Solar Gadgets",
    image: "https://images.unsplash.com/photo-1519750157634-b6d493a0f77c?auto=format&fit=crop&w=800&q=70",
    ecoScore: 5,
    rating: 4.8,
    reviewsCount: 342,
    ownerId: "seed",
    specs: {
      "Solar cell": "Monocrystalline 2.5 W",
      Battery: "4000 mAh lithium",
      Runtime: "40 h low / 8 h high",
      "Water rating": "IP68",
    },
  },
  {
    id: "p-reusable-bottle",
    title: "Insulated Steel Bottle",
    shortDescription: "Double-walled stainless bottle — 24h cold, 12h hot.",
    fullDescription:
      "Vacuum-insulated 18/8 stainless steel bottle with a leakproof bamboo cap. Powder-coated with a chip-resistant food-safe finish. Every bottle purchased removes 1kg of plastic waste from the ocean.",
    price: 32,
    category: "Zero-Waste Living",
    image: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=800&q=70",
    ecoScore: 5,
    rating: 4.9,
    reviewsCount: 981,
    ownerId: "seed",
    specs: {
      Capacity: "750 ml",
      Material: "18/8 stainless steel",
      Cap: "FSC bamboo + silicone seal",
      "Cold retention": "24 hours",
    },
  },
  {
    id: "p-hemp-tshirt",
    title: "Organic Hemp T-Shirt",
    shortDescription: "Breathable hemp-cotton blend, natural undyed finish.",
    fullDescription:
      "Made from 55% organic hemp and 45% GOTS-certified organic cotton. Naturally antimicrobial, gets softer with every wash. Cut and sewn in a fair-trade facility in Portugal.",
    price: 38,
    category: "Organic Apparel",
    image: "https://images.unsplash.com/photo-1618354691373-d851c5c3a990?auto=format&fit=crop&w=800&q=70",
    ecoScore: 4,
    rating: 4.5,
    reviewsCount: 214,
    ownerId: "seed",
    specs: {
      Fabric: "55% hemp / 45% organic cotton",
      Certifications: "GOTS, Fair Trade",
      Origin: "Portugal",
    },
  },
  {
    id: "p-solar-charger",
    title: "Foldable Solar Panel Charger 24W",
    shortDescription: "Dual USB-C output for phones, tablets, and small devices.",
    fullDescription:
      "A 24W foldable solar panel with three high-efficiency SunPower cells. Weighs 620g, folds to the size of a paperback. Weather-resistant Cordura shell and reinforced eyelets for hanging on a backpack.",
    price: 89,
    category: "Solar Gadgets",
    image: "https://images.unsplash.com/photo-1508514177221-188b1cf16e9d?auto=format&fit=crop&w=800&q=70",
    ecoScore: 4,
    rating: 4.6,
    reviewsCount: 156,
    ownerId: "seed",
  },
  {
    id: "p-beeswax-wraps",
    title: "Beeswax Food Wraps (Set of 5)",
    shortDescription: "Reusable food wraps — replaces 90 rolls of plastic wrap.",
    fullDescription:
      "Handmade wraps of organic cotton, sustainably sourced beeswax, tree resin, and jojoba oil. Naturally antibacterial. One set typically lasts a full year of daily kitchen use.",
    price: 24,
    category: "Zero-Waste Living",
    image: "https://images.unsplash.com/photo-1584727638096-042c45049ebe?auto=format&fit=crop&w=800&q=70",
    ecoScore: 5,
    rating: 4.7,
    reviewsCount: 512,
    ownerId: "seed",
  },
  {
    id: "p-bamboo-toothbrush",
    title: "Bamboo Toothbrush 4-Pack",
    shortDescription: "Biodegradable handle with plant-based bristles.",
    fullDescription:
      "Four toothbrushes with Moso bamboo handles and castor-oil bristles. The handle composts in 4-6 months. Comes in a recycled-paper box printed with soy ink.",
    price: 12,
    category: "Bamboo Tech",
    image: "https://images.unsplash.com/photo-1607613009820-a29f7bb81c04?auto=format&fit=crop&w=800&q=70",
    ecoScore: 5,
    rating: 4.4,
    reviewsCount: 289,
    ownerId: "seed",
  },
  {
    id: "p-solar-watch",
    title: "Solar-Powered Smart Watch",
    shortDescription: "Ambient light charging — never plug it in again.",
    fullDescription:
      "The Helios Solar Watch charges from sunlight and indoor light. GPS, heart rate, SpO2, and 10 days of typical battery life. Aluminum body recycled from post-consumer electronics.",
    price: 259,
    category: "Solar Gadgets",
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800&q=70",
    ecoScore: 4,
    rating: 4.6,
    reviewsCount: 87,
    ownerId: "seed",
  },
  {
    id: "p-jute-rug",
    title: "Handwoven Jute Rug",
    shortDescription: "Chunky natural-fiber rug, GoodWeave certified.",
    fullDescription:
      "A 5x8 rug hand-woven in India from 100% jute. GoodWeave certified against child labor. Fully biodegradable at end of life.",
    price: 189,
    category: "Eco Home",
    image: "https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?auto=format&fit=crop&w=800&q=70",
    ecoScore: 4,
    rating: 4.5,
    reviewsCount: 62,
    ownerId: "seed",
  },
  {
    id: "p-compost-bin",
    title: "Countertop Compost Bin",
    shortDescription: "Odor-locking charcoal filter, 5L capacity.",
    fullDescription:
      "Powder-coated steel countertop compost bin with a dual charcoal filter that traps odors for weeks. Fits neatly on any counter. Includes 6 replacement filters.",
    price: 42,
    category: "Eco Home",
    image: "https://images.unsplash.com/photo-1610348725531-843dff563e2c?auto=format&fit=crop&w=800&q=70",
    ecoScore: 4,
    rating: 4.3,
    reviewsCount: 174,
    ownerId: "seed",
  },
  {
    id: "p-organic-jeans",
    title: "Organic Cotton Jeans",
    shortDescription: "Washed with 90% less water than conventional denim.",
    fullDescription:
      "Classic straight-leg jeans made from 100% GOTS-certified organic cotton. Woven at a mill powered by wind energy. Ozone-washed, saving 90% of the water a standard rinse uses.",
    price: 98,
    category: "Organic Apparel",
    image: "https://images.unsplash.com/photo-1542272604-787c3835535d?auto=format&fit=crop&w=800&q=70",
    ecoScore: 4,
    rating: 4.4,
    reviewsCount: 231,
    ownerId: "seed",
  },
  {
    id: "p-bamboo-speaker",
    title: "Bamboo Bluetooth Speaker",
    shortDescription: "Warm acoustic sound in a solid bamboo enclosure.",
    fullDescription:
      "A 20W Bluetooth 5.3 speaker carved from a single block of bamboo. 15-hour battery, USB-C fast charge, IPX5 water resistance. Repairable — every part replaceable with a screwdriver.",
    price: 149,
    category: "Bamboo Tech",
    image: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&w=800&q=70",
    ecoScore: 5,
    rating: 4.7,
    reviewsCount: 198,
    ownerId: "seed",
  },
];

export const SEED_REVIEWS: Review[] = [
  { id: "r1", productId: "p-bamboo-keyboard", author: "Priya S.", rating: 5, comment: "Absolutely gorgeous and quieter than any keyboard I've owned.", date: "2025-11-04" },
  { id: "r2", productId: "p-bamboo-keyboard", author: "Marcus D.", rating: 4, comment: "Fantastic build, wish the arrow keys were a hair larger.", date: "2025-10-22" },
  { id: "r3", productId: "p-solar-lantern", author: "Lena K.", rating: 5, comment: "Took it on a 5-day trek. Never needed to plug it in.", date: "2025-12-01" },
  { id: "r4", productId: "p-reusable-bottle", author: "Jordan T.", rating: 5, comment: "Kept ice cubes solid for 22 hours in the sun.", date: "2026-01-18" },
];
