/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ItemsManageRouteImport } from './routes/items.manage'
import { Route as ItemsAddRouteImport } from './routes/items.add'
import { Route as ItemsIdRouteImport } from './routes/items.$id'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsManageRoute = ItemsManageRouteImport.update({
  id: '/items/manage',
  path: '/items/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsAddRoute = ItemsAddRouteImport.update({
  id: '/items/add',
  path: '/items/add',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsIdRoute = ItemsIdRouteImport.update({
  id: '/items/$id',
  path: '/items/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/items/$id': typeof ItemsIdRoute
  '/items/add': typeof ItemsAddRoute
  '/items/manage': typeof ItemsManageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/items/$id': typeof ItemsIdRoute
  '/items/add': typeof ItemsAddRoute
  '/items/manage': typeof ItemsManageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/items/$id': typeof ItemsIdRoute
  '/items/add': typeof ItemsAddRoute
  '/items/manage': typeof ItemsManageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/explore'
    | '/login'
    | '/register'
    | '/items/$id'
    | '/items/add'
    | '/items/manage'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/explore'
    | '/login'
    | '/register'
    | '/items/$id'
    | '/items/add'
    | '/items/manage'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/explore'
    | '/login'
    | '/register'
    | '/items/$id'
    | '/items/add'
    | '/items/manage'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ExploreRoute: typeof ExploreRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ItemsIdRoute: typeof ItemsIdRoute
  ItemsAddRoute: typeof ItemsAddRoute
  ItemsManageRoute: typeof ItemsManageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items/manage': {
      id: '/items/manage'
      path: '/items/manage'
      fullPath: '/items/manage'
      preLoaderRoute: typeof ItemsManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items/add': {
      id: '/items/add'
      path: '/items/add'
      fullPath: '/items/add'
      preLoaderRoute: typeof ItemsAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items/$id': {
      id: '/items/$id'
      path: '/items/$id'
      fullPath: '/items/$id'
      preLoaderRoute: typeof ItemsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ExploreRoute: ExploreRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ItemsIdRoute: ItemsIdRoute,
  ItemsAddRoute: ItemsAddRoute,
  ItemsManageRoute: ItemsManageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
